---
- name: Update system and install pip and docker
  hosts: all
  become: true

  vars:
    pip_install_packages:
      - name: docker

  pre_tasks:
    - name: System upgrade
      ansible.builtin.apt:
        upgrade: dist
        update_cache: true

  roles:
    - geerlingguy.pip
    - geerlingguy.docker
